# Generated by Django 5.2.1 on 2025-10-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0003_remove_warga_alamat'),
    ]

    operations = [
        migrations.AddField(
            model_name='warga',
            name='alamat',
            field=models.TextField(default='', verbose_name='Alamat Tinggal'),
        ),
    ]
